version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - exercise
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pedbot

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks:
    - exercise
    environment:
      - PMA_ARBITRARY=1
volumes:
  mysql-data:
networks:
  exercise:
